# Client Service Configuration

client:
  client_id: "client-001"
  coordinator_host: "localhost"
  coordinator_port: 50051
  
training:
  local_epochs: 5
  batch_size: 32
  learning_rate: 0.001
  optimizer: "adam"
  model_type: "simple_cnn"
  dataset: "mnist"
  
privacy:
  epsilon: 1.0
  delta: 1e-5
  max_grad_norm: 1.0
  noise_multiplier: 1.0
  
data:
  data_dir: "data/"
  validation_split: 0.1
  download_data: true
  
device:
  use_cuda: true
  device_id: 0
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/client.log"
  
checkpoints:
  save_checkpoints: true
  checkpoint_dir: "checkpoints/"
  save_frequency: 5