# Coordinator Service Configuration

server:
  host: "0.0.0.0"
  grpc_port: 50051
  http_port: 8080
  max_workers: 10

federated_learning:
  min_clients: 2
  max_clients: 50
  round_timeout: 300  # seconds
  aggregation_algorithm: "fedavg"
  
privacy:
  default_epsilon: 1.0
  default_delta: 1e-5
  max_grad_norm: 1.0
  noise_multiplier: 1.0

database:
  url: "postgresql://federated:password@localhost:5432/federated_learning"
  pool_size: 10
  max_overflow: 20

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/coordinator.log"

monitoring:
  enable_metrics: true
  metrics_port: 9090
  health_check_interval: 30